### ISSUE TITLE
Daisy with opencv

### ISSUE THREAD

**Issue by mpkuse** [etola/libdaisy#3]
Hi,
I am trying to explore the daisy descriptor. I found it convenient to use opencv's daisy implementation. 

My code https://github.com/mpkuse/robust_feature_matching/blob/master/daisy_keypoints.cpp

The daisy descriptors compute a 200-dimensional vector at every pixel. My question is using a
simple FLANN based matcher to find nearest neighbors and then using a Lowe's ratio test a valid
and acceptable way to obtain point matches?

**Comment by etola** [comment]
you can do that but I'd recommend to limit the search space if you can - i.e. if you know the epipolar geometry, look for matches along the epipolar lines.

secondly, you don't have to compute a 200-vector for every task. For narrow baseline setups I often use 8-1-4-4 ( or 8-2-4-4 ) as the shape parameters instead of 15-3-8-8 and ending with a 20 (or 36)-dimensional description. You should check out M. Brown's 'Picking the best Daisy' paper

**Comment by mpkuse** [comment]
Thanks for suggestion. On another note, I am building up a python wrapper for your beautifully structured code! 

I hope you don't mind me asking a few questions as they come up for this?

**Comment by mpkuse** [comment]
I am a little bit confused as to after setting the float* array, which function should I call?

I am interested in getting the dense matrix, ie. MxNx20 (8,1,4,4 config). 
I set the float * array as set_image(). Then set params as set_parameters(8,1,4,4). 

Am i correct to compute_descriptors() followed by normalize_descriptors()?

**Comment by etola** [comment]
if you are asking about the opencv version - I'm not following that - I have no idea - you need to ask the maintainer.

if you are asking about this version, see the usage examples under src/main.cpp ( bear in mind that this is a piece of code I haven't updated for the last 6 years... )
